# Generated by Django 4.1.5 on 2023-02-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cake',
            new_name='Caken',
        ),
    ]
